### ISSUE TITLE
这是一个关于digital_life的issue

### ISSUE THREAD

**Issue by lkzs** [seanxpw/git_drive#1]
很抱歉，在这个仓库下提出关于digital_life的issue，因为在你fork的digital_life的仓库里无法提问题。
我是在Ubuntu上配置的，按照你的教程，但执行bash /Digital_Life_Server/run-gpt3.5-api.bat  后出现错误。
![image](https://github.com/seanxpw/git_drive/assets/72988153/7415f5c0-2c16-4c40-acb3-b1967792ef52)
我在极客湾仓库里没找到类似的问题，所以想请求你的帮助，跪谢！

**Comment by seanxpw** [comment]
你好，感谢issue 
我刚刚把那个仓库打开了issue功能
我们到在那边去说hhh
你的截图不太全
看报错是极客湾他们的api用的人太多了现在满了
你可以等一会儿再试试
也可以换成自己的api（如果有的话）
